### ISSUE TITLE
增量更新数据的时候 请问关于复权的事情应该如何处理呢

### ISSUE THREAD

**Issue by jijivski** [wukan1986/ddump#1]
如果昨天股票分红或者拆股 
那么今天下载的上周五数据和上周末下载的上周五数据会不一样，所以上次下的数据失效了
（问题似乎无关代码，请问有无方案推荐

**Comment by wukan1986** [comment]
1.  下载行情时都下载原始价格数据（未复权），所以原则上不会出现历史数据发生改的情况
2.  另下载或计算**后**复权因子。这个因子的特点是历史值不会发生修正。将开高低收乘复权因子得到后复权价

`examples/jqresearch/get_price_stock_daily.py`中就是按此下载的数据

**Comment by jijivski** [comment]
明白！ 感谢
都说前复权对查看当下价格方便，但想了想 实际上计算指标和信号的时候一样的。
